# Setup
title:        Edward Feng
tagline:      INSPIRE. INFLUENCE. IMPACT
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Edward Feng
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown