# Setup
title:        Edward Feng
tagline:      Computer Science, Sophomore at the University of Toronto
baseurl:      ""
paginate:     1

# About/contact
author: Edward Feng

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown