# Setup
title:        Edward Feng
tagline:      INSPIRE. INFLUENCE. IMPACT.
baseurl:      ""
paginate:     1

# About/contact
author: Edward Feng

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown